import React, { useEffect } from "react";
import MainLayout from "../layout/MainLayout";
import Head from "next/head";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/bootstrap-icons.css";
import "../../public/assets/css/fontawesome.min.css";
import "../../public/assets/css/boxicons.min.css";
import "../../public/assets/css/all.min.css";
import "../../public/assets/css/swiper-bundle.min.css";
import "../../public/assets/css/nice-select.css";
import "../../public/assets/css/animate.min.css";
import "../../public/assets/css/style.css";

export default function App({ Component, pageProps }) {
  useEffect(() => {
    import("../../public/assets/js/bootstrap.min.js");
  }, []);
  return (
    <>
      <Head>
        <title>Drivco - Car Dealer NExt Js Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MainLayout>
        <Component {...pageProps} />
      </MainLayout>
    </>
  );
}
