import Head from 'next/head';
import Banner from '../components/banner/Banner';
import ChooseProduct from '../components/Home/ChooseProduct';

import NewestProduct from '../components/Home/NewestProduct';
import InstagramSection from '../components/Home/InstagramSection';
import { fetchBanners } from '../data/bannerData';
import { fetchProducts } from '../data/productList';

export default function Home({ banners, products }) {
  return (
    <>
      <Head>
        <title>Beautico - Beauty & Cosmetics Next Js Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>

      <Banner banners={banners} />
      <ChooseProduct />

      {/* Pass fetched products as props */}
      {products && <NewestProduct products={products} />}
      <InstagramSection />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const banners = await fetchBanners();
    const productsResponse = await fetchProducts({ ordering: '-id' });
    console.log(productsResponse);
    return {
      props: {
        banners: Array.isArray(banners) ? banners : [],
        products: productsResponse?.results || [], // Ensure products is an array
      },
    };
  } catch (error) {
    console.error('Error fetching data:', error);
    return {
      props: {
        banners: [],
        products: [], // Return an empty array in case of error
      },
    };
  }
}
