import Head from 'next/head';
import Banner from '../components/banner/Banner';
import ChooseProduct from '../components/Home/ChooseProduct';
import BestSellingProduct from '../components/Home/BestSellingProduct';
import NewestProduct from '../components/Home/NewestProduct';
import InstagramSection from '../components/Home/InstagramSection';
import { fetchBanners } from '../data/bannerData';

export default function Home({ banners }) {
  return (
    <>
      <Head>
        <title>Beautico - Beauty & Cosmetics Next Js Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>

      <Banner banners={banners} />
      <ChooseProduct />
      <BestSellingProduct />
      <NewestProduct />
      <InstagramSection />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const banners = await fetchBanners();
    return {
      props: {
        banners: Array.isArray(banners) ? banners : [],
      },
    };
  } catch (error) {
    console.error('Error fetching banners:', error);
    return {
      props: {
        banners: [], // Return an empty array in case of error
      },
    };
  }
}
