import React, { useContext } from 'react';
import Footer from './Footer';
import AuthModal from './AuthModal';
import Breadcrumb from '../components/common/Breadcrumb';
import { useRouter } from 'next/router';
import Header2 from './Header2';
import Head from 'next/head';
import { AuthContext } from '../store/authcontext';
import Topbar from './Topbar';
const MainLayout = ({ children }) => {
  const route = useRouter();
  const { isLoggedIn, logout } = useContext(AuthContext); // Get isLoggedIn and logout from context

  const handleLogout = async () => {
    await logout(); // Call the logout function from context
  };

  return (
    <>
      <Head>
        <title>{`Beautico - ${route.pathname}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>
      <Topbar />
      <Header2 />
      {route.pathname === '/' ? <></> : <Breadcrumb />}
      {!isLoggedIn && <AuthModal />}
      {children}
      <Footer />
    </>
  );
};

export default MainLayout;
